In [8]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [27]:
# df = pd.read_excel(r"C:\Users\mturky\Documents\june 2026 ind.xlsx")

data = pd.read_excel(r"C:\Users\mturky\Documents\june 2026 ind.xlsx", dtype='str')

In [28]:
data.iloc[647]['inv_Period From']

'2026-06-11 00:00:00'

In [29]:
display(df.iloc[[647]].T)

                                                   647
inv_Subscriber Nr                             12456237
inv_Doc Type                                   Invoice
inv_Ftnr                                   INV_9010166
inv_Created Date                   2026-06-11 00:00:00
inv_Created Time                           01:00:42 AM
inv_Doc Status                                  Posted
inv_Period From                    2026-06-11 00:00:00
inv_Period To                      2026-09-10 00:00:00
inv_Amount                                         735
inv_User Name                               Mobile_App
inv_Default Entity Type                CNE Head Office
inv_Smartcard                              42916908983
inv_Bill Period                11/06/2026 - 10/09/2026
inv_Bill Cycle                                      3M
inv_Invoice Type                  Subscription Invoice
inv_Plan Name                           TOGETHER 09.24
inv_Contract Number                            4246137
inv_Subscriber Type           beIN Quartar Installment
inv_Subscriber Entity                  CNE Head office
pmt_Amount                                       735.0
pmt_Ftnr                                CNEPMT_2343157
Docinternalid                       CNE_RCT_SW_2139435
flag                            One to One (Same Date)
inv_Bank Date                                      NaN
inv_User Fullname                                  NaN
inv_Payment Ref No                                 NaN
inv_Event Description                              NaN
inv_Payment Batch No                               NaN
inv_Batch Approval No                              NaN
inv_Collecting Entity                              NaN
inv_Pay Mode                                       NaN
inv_Jv Type                                        NaN
inv_Book Number                                    NaN
inv_Channel Provider                               NaN
inv_Last Four Digits Of Card                       NaN
inv_PAYMENT_FLAG                                   NaN
inv_DS_PAYMENT_FLAG                                NaN

In [25]:
data.iloc[647]['inv_Period From']

'2026-05-15 00:00:00'

In [26]:
data['inv_Period From'] = pd.to_datetime(data['inv_Period From'])

In [16]:
display(df.iloc[[646]]['inv_Subscriber Nr'])
display(df.iloc[[647]])

646    12454272
Name: inv_Subscriber Nr, dtype: object

,inv_Subscriber Nr,inv_Doc Type,inv_Ftnr,inv_Created Date,inv_Created Time,inv_Doc Status,inv_Period From,inv_Period To,inv_Amount,inv_User Name,inv_Default Entity Type,inv_Smartcard,inv_Bill Period,inv_Bill Cycle,inv_Invoice Type,inv_Plan Name,inv_Contract Number,inv_Subscriber Type,inv_Subscriber Entity,pmt_Amount,pmt_Ftnr,Docinternalid,flag,inv_Bank Date,inv_User Fullname,inv_Payment Ref No,inv_Event Description,inv_Payment Batch No,inv_Batch Approval No,inv_Collecting Entity,inv_Pay Mode,inv_Jv Type,inv_Book Number,inv_Channel Provider,inv_Last Four Digits Of Card,inv_PAYMENT_FLAG,inv_DS_PAYMENT_FLAG
647,12456237,Invoice,INV_9010166,2026-06-11 00:00:00,01:00:42 AM,Posted,2026-06-11 00:00:00,2026-09-10 00:00:00,735,Mobile_App,CNE Head Office,42916908983,11/06/2026 - 10/09/2026,3M,Subscription Invoice,TOGETHER 09.24,4246137,beIN Quartar Installment,CNE Head office,735.0,CNEPMT_2343157,CNE_RCT_SW_2139435,One to One (Same Date),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.loc[df['inv_Subscriber Nr']==12454272]

,inv_Subscriber Nr,inv_Doc Type,inv_Ftnr,inv_Created Date,inv_Created Time,inv_Doc Status,inv_Period From,inv_Period To,inv_Amount,inv_User Name,inv_Default Entity Type,inv_Smartcard,inv_Bill Period,inv_Bill Cycle,inv_Invoice Type,inv_Plan Name,inv_Contract Number,inv_Subscriber Type,inv_Subscriber Entity,pmt_Amount,pmt_Ftnr,Docinternalid,flag,inv_Bank Date,inv_User Fullname,inv_Payment Ref No,inv_Event Description,inv_Payment Batch No,inv_Batch Approval No,inv_Collecting Entity,inv_Pay Mode,inv_Jv Type,inv_Book Number,inv_Channel Provider,inv_Last Four Digits Of Card,inv_PAYMENT_FLAG,inv_DS_PAYMENT_FLAG
646,12454272,Invoice,INV_9023256,2026-06-12 00:00:00,12:30:37 AM,Posted,2026-06-16 00:00:00,2026-07-15 00:00:00,507,SYSADMIN,CNE Head Office,42912476217,16/06/2026 - 15/07/2026,1M,Subscription Invoice,PREMIUM 09.24,3727777,BeIN sports CC,Mohandeseen Showroom,507.0,CNEPMT_2348480,CNE_RCT_SW_2150535,One to One (Same Date),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN