In [67]:
import pandas as pd
import numpy as np
import re
import os
from pathlib import Path
from functions import search_files

In [68]:
filename = search_files("BEINDATANEWRPT")[0]
print(filename)
bein_src = pd.read_csv( filename, dtype='str')

s:\28.09.26\30988646_BEINDATANEWRPT.CSV

In [103]:
startdate = "2026-10-01"
enddate = "2026-10-31"

In [109]:
bein = bein_src.copy()
bein['End Date'] = pd.to_datetime(bein['End Date'] , dayfirst=True, errors='coerce')
bein['Next Billing Date'] = pd.to_datetime(bein['Next Billing Date'] , dayfirst=True,errors='coerce')
bein = bein.dropna(subset=['End Date','Next Billing Date'])


main_pck_filter = (
            bein["Plan"].str.contains(
                "prem",
                case=False,
                na=False
            )
            |
            bein["Plan"].str.contains(
                "ulti",
                case=False,
                na=False
            )
            |
            bein["Plan"].str.contains(
                "toget",
                case=False,
                na=False
            )
        )


bein = bein.loc[main_pck_filter]
# bein = bein.sort_values(['Customer Number','End Date'], ascending=[True,False])


bein = bein.sort_values(['Customer Number', 'Status'] , ascending=[True,True])

bein = bein.drop_duplicates(subset=['Customer Number'], keep='first')

In [110]:
display (bein.loc[bein['Smart Card']=='10611577163'])

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance
1363568,18199925,beIN Quartar Installment,Marsa Matruh,3817051,01-10-2025,2026-09-30,PREMIUM 09.24,Active,0315435598,Humax HD-Mini,10611577163,CNE V7 Card,2026-10-01,3M,0 Dr,0 Dr,0 Dr

In [111]:

conditions = [
    # CNE Head office
    bein['Entity'].str.contains('CNE Head office', case=False, na=False)
    | bein['Entity'].str.contains('r2s', case=False, na=False)
    | bein['Entity'].str.contains('cne commercial', case=False, na=False)
    | bein['Entity'].str.contains('FAWRY PLUS', case=False, na=False)
    | bein['Entity'].str.contains('Maintainance', case=False, na=False)
    | bein['Entity'].str.contains('E-Shop', case=False, na=False),
    
    # beIN Head office
    bein['Entity'].str.contains('beIN Head office', case=False, na=False)
    | bein['Entity'].str.contains('bein commercial', case=False, na=False)
    | bein['Entity'].str.contains('beIN Showroom', case=False, na=False),

    # beIN Show Room
    bein['Entity'].str.contains(r'beIN\s*Show', case=False, na=False),

    # CNE Show Room
    bein['Entity'].str.contains('Room', case=False, na=False),

    # beIN Dealers
    bein['Entity'].str.contains('bein', case=False, na=False)

]

choices = [
    'CNE Head office',
    'beIN Head office',
    'beIN Show Room',
    'CNE Show Room',
    'beIN Dealers'
]

bein['Depot'] = np.select(
    conditions,
    choices,
    default='CNE Dealers'
)

In [112]:
bein_cne_dealers = bein.loc[bein['Depot']=='CNE Dealers']

In [113]:
dealers_next_month_ced = bein_cne_dealers.loc[bein_cne_dealers['End Date'].between(pd.to_datetime(startdate),pd.to_datetime(enddate))]
list_cne_ced =  dealers_next_month_ced['Entity'].unique()

dealers_next_month_nid = bein_cne_dealers.loc[bein_cne_dealers['Next Billing Date'].between(pd.to_datetime(startdate),pd.to_datetime(enddate))]
list_cne_nid =  dealers_next_month_nid['Entity'].unique()


dealers_next_month_ced = dealers_next_month_ced.loc[~dealers_next_month_ced['Customer Type'].isin(['Corporate Subscriber','Illegal Network', 'Head End','BeIN sports CC'])]
dealers_next_month_nid = dealers_next_month_nid.loc[~dealers_next_month_nid['Customer Type'].isin(['Corporate Subscriber','Illegal Network', 'Head End','BeIN sports CC'])]


dealers_all = pd.concat([dealers_next_month_ced,dealers_next_month_nid]).drop_duplicates(['Customer Number'], keep='first')




# dealers_all = dealers_all.loc[~dealers_all['Customer Type'].isin(['Corporate Subscriber','Illegal Network', 'Head End','BeIN sports CC'])]

In [114]:
dealers_all['Customer Type'].unique()

array(['CNE Subscriber', 'beIN Quartar Installment',
       'beIN Bi Installment', 'Bein NC'], dtype=object)

In [115]:
dealers_next_month_ced.to_csv('branches/dealers_ced.csv', index=False)
dealers_next_month_nid.to_csv('branches/dealers_nbd.csv', index=False)
dealers_all.to_csv('branches/dealers all.csv', index=False)

In [116]:
print(dealers_next_month_ced.shape[0])
print(dealers_next_month_ced.drop_duplicates(subset='Customer Number').shape[0])

7476
7476

In [117]:
os.makedirs(r'branches/ced', exist_ok=True)
os.makedirs(r'branches/nid', exist_ok=True)




for file in Path(r'branches/ced').iterdir():
    if file.is_file():
        file.unlink()

for file in Path(r'branches/nid').iterdir():
    if file.is_file():
        file.unlink()

In [118]:

for branch in list_cne_ced:
    filename = re.sub(r'[<>:"/\\|?*]', '_', branch)
    dealers_next_month_ced.loc[dealers_next_month_ced['Entity']==branch].drop(columns=['Depot']).to_csv(f'branches/ced/{filename}.csv',index = False)


for branch in list_cne_ced:
    filename = re.sub(r'[<>:"/\\|?*]', '_', branch)
    dealers_next_month_nid.loc[dealers_next_month_nid['Entity']==branch].drop(columns=['Depot']).to_csv(f'branches/nid/{filename}.csv',index = False)

In [119]:

display (dealers_next_month_ced.loc[dealers_next_month_ced['Smart Card']=='10611577163'])
display (dealers_next_month_nid.loc[dealers_next_month_nid['Smart Card']=='10611577163'])
display (dealers_all.loc[dealers_all['Smart Card']=='10611577163'])

Empty DataFrame
Columns: [Customer Number, Customer Type, Entity, Contract Number, Start Date, End Date, Plan, Status, Decoder, Item Description STB, Smart Card, Item Description SC, Next Billing Date, Billing Cycle, PPV Balance, Customer Balance, Outstanding Balance, Depot]
Index: []

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance,Depot
1363568,18199925,beIN Quartar Installment,Marsa Matruh,3817051,01-10-2025,2026-09-30,PREMIUM 09.24,Active,0315435598,Humax HD-Mini,10611577163,CNE V7 Card,2026-10-01,3M,0 Dr,0 Dr,0 Dr,CNE Dealers

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance,Depot
1363568,18199925,beIN Quartar Installment,Marsa Matruh,3817051,01-10-2025,2026-09-30,PREMIUM 09.24,Active,0315435598,Humax HD-Mini,10611577163,CNE V7 Card,2026-10-01,3M,0 Dr,0 Dr,0 Dr,CNE Dealers