In [93]:
import pandas as pd
from datetime import datetime , timedelta

yesterday = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')

In [94]:
detailed = pd.read_csv(r"C:\Users\mturky\Downloads\30880509_DETAILNEWANDREN.CSV", dtype='str')
disconnection = pd.read_csv(r"C:\Users\mturky\Downloads\30880508_DailyDisconnectionReport.CSV", dtype='str')

In [95]:
sub_types = ['beIN Quartar Installment'
             , 'CNE Subscriber'
             , 'MCE staff (CNE staff)'
             ,'BeIN sports CC'
             , 'beIN Bi Installment'
             , 'Corporate Subscriber'
             , 'Bein NC'
             , 'Bulk DTH customer'
             , 'beIN Installment Sub']

In [96]:
detailed['Effective Date'] = pd.to_datetime(
    detailed['Effective Date'],
    dayfirst=True
).dt.strftime('%Y-%m-%d')


disconnection['ACTION_DATE_3'] = pd.to_datetime(
    disconnection['ACTION_DATE_3'],
    dayfirst=True
).dt.strftime('%Y-%m-%d')

C:\Users\mturky\AppData\Local\Temp\1\ipykernel_29128\3887876157.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  detailed['Effective Date'] = pd.to_datetime(

In [97]:
detailed['Event'].unique()

array(['New Agreement For Existing Customer', 'New Agreement', 'Renewal',
       'Reconnected', 'Activated from Suspension'], dtype=object)

In [98]:
detailed = detailed.loc[detailed['Effective Date'] == yesterday]

detailed = detailed.loc[(detailed['Package'].str.contains('prem',case=False))
                        |(detailed['Package'].str.contains('ulti',case=False))
                        |(detailed['Package'].str.contains('toget',case=False))]

detailed = detailed.loc[detailed['Customer Type'].isin(sub_types)]

detailed_renewal = detailed.loc[detailed['Event'].isin(['New Agreement For Existing Customer', 'Renewal'])]
detailed = detailed.loc[detailed['Event'].isin(['New Agreement For Existing Customer', 'Activated from Suspension'])]

In [99]:
new_for_existing = detailed.loc[detailed['Event']=='New Agreement For Existing Customer']
activated_from_suspension = detailed.loc[detailed['Event']=='Activated from Suspension']

In [100]:
disconnection = disconnection.loc[(disconnection['AFFECTED_PLAN_5'].str.contains('prem',case=False))
                        |(disconnection['AFFECTED_PLAN_5'].str.contains('ulti',case=False))
                        |(disconnection['AFFECTED_PLAN_5'].str.contains('toget',case=False))]

In [101]:
disconnection = disconnection.drop_duplicates(subset=['CUSTOMER_NUMBER_1'])

In [102]:
new_none_common = new_for_existing.loc[~new_for_existing['Customer Number'].isin(disconnection['CUSTOMER_NUMBER_1'])]

In [103]:
common_with_renewal = detailed_renewal.loc[detailed_renewal['Customer Number'].isin(disconnection['CUSTOMER_NUMBER_1'])]
common_with_renewal

,Customer Number,Smart Card Number,Reconnection Reason,Event,Effective Date,Package,Customer Type,Contract End Date,User
5,14722383,10709030125,New Agreement,New Agreement For Existing Customer,2026-09-06,Premium 6 Months,CNE Subscriber,05-03-2027 00:00:00,EDD MENOFIYA user1
8,18977658,10679775188,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,EDD KAFR ELZAYAT user3
13,13907315,10709154560,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,CNE Subscriber,05-09-2027 00:00:00,Mobile_App
14,16412204,10388480781,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,Mobile_App
15,18211187,10611587543,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,CNE Subscriber,05-09-2027 00:00:00,Mobile_App
...,...,...,...,...,...,...,...,...,...
1689,18432130,10618692791,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,CNE Subscriber,05-09-2027 00:00:00,Mobile_App
1690,18435665,10618650849,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,CNE Subscriber,05-09-2027 00:00:00,Mobile_App
1698,18073511,10570293786,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 6m BTL 2026,CNE Subscriber,05-03-2027 00:00:00,Mohamed Khaled Mohamed Tawfik Shebl
1707,15022000,42768489462,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,EDD ALEX4 user4
1717,19169234,10732695621,New Agreement,New Agreement For Existing Customer,2026-09-06,ULTIMATE 09.24,CNE Subscriber,05-09-2027 00:00:00,FAWRY PAYMENT LINK

In [104]:
total_reinstatment = pd.concat([new_none_common,activated_from_suspension])
total_reinstatment

,Customer Number,Smart Card Number,Reconnection Reason,Event,Effective Date,Package,Customer Type,Contract End Date,User
0,15882664,10161880504,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,MAHMOUD SABRY
3,19037357,10709175045,New Agreement,New Agreement For Existing Customer,2026-09-06,ULTIMATE 09.24,CNE Subscriber,05-09-2027 00:00:00,EDD QOBA NEW user4
10,19189783,10732810253,New Agreement,New Agreement For Existing Customer,2026-09-06,Premium 6 Months,CNE Subscriber,05-03-2027 00:00:00,ABDALLAH DARWISH HAMED
11,18716570,10731036751,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,CNE Subscriber,05-09-2027 00:00:00,FAWRY
12,19019193,10691075914,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,FAWRY
...,...,...,...,...,...,...,...,...,...
1781,19093947,10697230802,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-12-2026 00:00:00,Mobile_App
1783,17821748,10570257195,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,03-03-2027 00:00:00,FAWRY
1785,18707194,10509213517,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,07-02-2027 00:00:00,EDD ISMAILIA user1
1786,16946102,10388548983,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,25-01-2027 00:00:00,EDD Omrania user1
1788,18955726,10676384687,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,26-02-2027 00:00:00,Mobile_App

In [105]:
subs = ['beIN Quartar Installment',
       'beIN Bi Installment', 'BeIN sports CC', 'Corporate Subscriber']

total_reinstatment.loc[total_reinstatment['Customer Type'].isin(subs)]

,Customer Number,Smart Card Number,Reconnection Reason,Event,Effective Date,Package,Customer Type,Contract End Date,User
0,15882664,10161880504,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,MAHMOUD SABRY
12,19019193,10691075914,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,FAWRY
18,19163682,10731066956,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,EDD Omrania user2
22,18963672,10676372898,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-09-2027 00:00:00,Hazem Mohamed Monier Mohamed
25,19104730,10719621830,New Agreement,New Agreement For Existing Customer,2026-09-06,PREMIUM 09.24,beIN Bi Installment,05-09-2027 00:00:00,beIN Kafr el sheikh user 5
...,...,...,...,...,...,...,...,...,...
1781,19093947,10697230802,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,05-12-2026 00:00:00,Mobile_App
1783,17821748,10570257195,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,03-03-2027 00:00:00,FAWRY
1785,18707194,10509213517,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,07-02-2027 00:00:00,EDD ISMAILIA user1
1786,16946102,10388548983,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,25-01-2027 00:00:00,EDD Omrania user1
1788,18955726,10676384687,Activated from Suspension,Activated from Suspension,2026-09-06,PREMIUM 09.24,beIN Quartar Installment,26-02-2027 00:00:00,Mobile_App