In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [13]:
data = pd.read_csv(r"S:\Doaa 12.12.255\26659164_NEWCNEFINTRANSRPT.CSV",dtype = 'str')

In [14]:
data

,Subscriber Nr,Doc Type,Ftnr,Created Date,Created Time,Doc Status,Period From,Period To,Bank Date,Amount,User Name,User Fullname,Payment Ref No,Event Description,Payment Batch No,Batch Approval No,Default Entity Type,Collecting Entity,Pay Mode,Jv Type,Book Number,Smartcard,Bill Period,Bill Cycle,Invoice Type,Plan Name,Contract Number,Channel Provider,Subscriber Type,Subscriber Entity,Last Four Digits Of Card,Payment Flag
0,10341370,Credit Note,CR_408829,21/09/2025 12:00:00 AM,02:51:32 PM,Posted,NaN,NaN,NaN,0.01,ASAMMIE,Ahmed Abdel Sammie,NaN,HUMAX 1000s forced swap,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,42916777537,NaN,NaN,NaN,NaN,NaN,beIN,Corporate Subscriber,CNE Head office,NaN,NaN
1,14008577,Credit Note,CR_408838,21/09/2025 12:00:00 AM,02:51:33 PM,Posted,NaN,NaN,NaN,0.01,ASAMMIE,Ahmed Abdel Sammie,NaN,HUMAX 1000s forced swap,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,42916807722,NaN,NaN,NaN,NaN,NaN,beIN,beIN Quartar Installment,Mansoura,NaN,NaN
2,13294054,Credit Note,CR_408845,21/09/2025 12:00:00 AM,02:51:33 PM,Posted,NaN,NaN,NaN,0.01,ASAMMIE,Ahmed Abdel Sammie,NaN,HUMAX 1000s forced swap,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,42916777263,NaN,NaN,NaN,NaN,NaN,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN
3,12832785,Credit Note,CR_408846,21/09/2025 12:00:00 AM,02:51:33 PM,Posted,NaN,NaN,NaN,0.01,ASAMMIE,Ahmed Abdel Sammie,NaN,HUMAX 1000s forced swap,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10679749571,NaN,NaN,NaN,NaN,NaN,beIN,CNE Subscriber,CNE Head office,NaN,NaN
4,13927777,Credit Note,CR_408850,21/09/2025 12:00:00 AM,02:51:34 PM,Posted,NaN,NaN,NaN,0.01,ASAMMIE,Ahmed Abdel Sammie,NaN,HUMAX 1000s forced swap,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,42916777131,NaN,NaN,NaN,NaN,NaN,beIN,beIN Quartar Installment,Alex 2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15066,17308758,Payment,CNEPMT_2109927,21/09/2025 12:00:00 AM,02:40:31 PM,Posted,NaN,NaN,NaN,3044,SAHL,SAHL,1724966,1050146915204,NaN,NaN,CNE Head Office,CNE Head office,Cash,NaN,NaN,10389005280,NaN,NaN,NaN,NaN,NaN,beIN,beIN Quartar Installment,CNE Head office,NaN,Normal payment
15067,EDDSHRM,Payment,CNEPMT_2109930,21/09/2025 12:00:00 AM,02:42:20 PM,Posted,NaN,NaN,NaN,24400,ASAAD,Ahmed Saad,NaN,instpay aaib ref 181,NaN,NaN,CNE Dealer,CNE Head office,CIB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sharm Elshik,NaN,NaN
15068,EDDKABA,Payment,CNEPMT_2109933,21/09/2025 12:00:00 AM,02:44:27 PM,Posted,NaN,NaN,NaN,30000,ASAAD,Ahmed Saad,NaN,instpay aaib ref 791,NaN,NaN,CNE Dealer,CNE Head office,CIB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kabaa,NaN,NaN
15069,16715984,Payment,CNEPMT_2109942,21/09/2025 12:00:00 AM,03:06:40 PM,Posted,NaN,NaN,NaN,14965,TFAHMY,TAMER FAHMY,1724973,100006993545,SEP 21/25 COMCNBK,NaN,CNE Head Office,Maadi showroom,Cash,NaN,NaN,10676325060,NaN,NaN,NaN,NaN,NaN,beIN,Clubs,CNE Commercial Warehouse,NaN,Commercial Payment
15070,11514173,Payment,CNEPMT_2109943,21/09/2025 12:00:00 AM,03:07:06 PM,Posted,NaN,NaN,NaN,507,SATTYA,Sherif atya,7584564692506576504072,NaN,NaN,NaN,CNE Head Office,CNE Head office,Credit Card,NaN,NaN,10719256454,NaN,NaN,NaN,NaN,NaN,beIN,BeIN sports CC,CNE Head office,NaN,Normal payment

In [15]:
data = data.loc[~((data['Doc Type']=='Credit Note') & (data["Event Description"]=="HUMAX 1000s forced swap") )]

In [19]:
data

,Subscriber Nr,Doc Type,Ftnr,Created Date,Created Time,Doc Status,Period From,Period To,Bank Date,Amount,User Name,User Fullname,Payment Ref No,Event Description,Payment Batch No,Batch Approval No,Default Entity Type,Collecting Entity,Pay Mode,Jv Type,Book Number,Smartcard,Bill Period,Bill Cycle,Invoice Type,Plan Name,Contract Number,Channel Provider,Subscriber Type,Subscriber Entity,Last Four Digits Of Card,Payment Flag
1781,19185920,Debit Note,DR_408770,21/09/2025 12:00:00 AM,09:49:49 AM,Posted,NaN,NaN,NaN,0.12,ASAMMIE,Ahmed Abdel Sammie,NaN,Wrong FT,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10732559348,NaN,NaN,NaN,NaN,NaN,beIN,MCE staff (CNE staff),Mohandeseen Showroom,NaN,NaN
1782,18933524,Debit Note,DR_408798,21/09/2025 12:00:00 AM,02:17:09 PM,Posted,NaN,NaN,NaN,535,EYASSIN,IHAB YASSIN,NaN,Permit fees,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10697144771,NaN,NaN,NaN,NaN,NaN,beIN,Clubs,CNE Commercial Warehouse,NaN,NaN
1783,19141770,Invoice,INV_8308067,21/09/2025 12:00:00 AM,12:05:20 AM,Posted,21/09/2025 12:00:00 AM,20/12/2025 12:00:00 AM,NaN,1522,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10730812988,21/09/2025 - 20/12/2025,3M,Subscription Invoice,PREMIUM 09.24,3460238,beIN,beIN Quartar Installment,EDD Omrania,NaN,NaN
1784,19094284,Invoice,INV_8308072,21/09/2025 12:00:00 AM,12:05:21 AM,Posted,21/09/2025 12:00:00 AM,20/12/2025 12:00:00 AM,NaN,2839,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10697307816,21/09/2025 - 20/12/2025,3M,Subscription Invoice,ULTIMATE 09.24,3460501,beIN,beIN Quartar Installment,Assuit 2,NaN,NaN
1785,14418026,Invoice,INV_8308081,21/09/2025 12:00:00 AM,12:05:25 AM,Posted,21/09/2025 12:00:00 AM,20/12/2025 12:00:00 AM,NaN,1522,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10719550518,21/09/2025 - 20/12/2025,3M,Subscription Invoice,PREMIUM 09.24,3460786,beIN,beIN Quartar Installment,Sharkia,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15066,17308758,Payment,CNEPMT_2109927,21/09/2025 12:00:00 AM,02:40:31 PM,Posted,NaN,NaN,NaN,3044,SAHL,SAHL,1724966,1050146915204,NaN,NaN,CNE Head Office,CNE Head office,Cash,NaN,NaN,10389005280,NaN,NaN,NaN,NaN,NaN,beIN,beIN Quartar Installment,CNE Head office,NaN,Normal payment
15067,EDDSHRM,Payment,CNEPMT_2109930,21/09/2025 12:00:00 AM,02:42:20 PM,Posted,NaN,NaN,NaN,24400,ASAAD,Ahmed Saad,NaN,instpay aaib ref 181,NaN,NaN,CNE Dealer,CNE Head office,CIB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sharm Elshik,NaN,NaN
15068,EDDKABA,Payment,CNEPMT_2109933,21/09/2025 12:00:00 AM,02:44:27 PM,Posted,NaN,NaN,NaN,30000,ASAAD,Ahmed Saad,NaN,instpay aaib ref 791,NaN,NaN,CNE Dealer,CNE Head office,CIB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kabaa,NaN,NaN
15069,16715984,Payment,CNEPMT_2109942,21/09/2025 12:00:00 AM,03:06:40 PM,Posted,NaN,NaN,NaN,14965,TFAHMY,TAMER FAHMY,1724973,100006993545,SEP 21/25 COMCNBK,NaN,CNE Head Office,Maadi showroom,Cash,NaN,NaN,10676325060,NaN,NaN,NaN,NaN,NaN,beIN,Clubs,CNE Commercial Warehouse,NaN,Commercial Payment
15070,11514173,Payment,CNEPMT_2109943,21/09/2025 12:00:00 AM,03:07:06 PM,Posted,NaN,NaN,NaN,507,SATTYA,Sherif atya,7584564692506576504072,NaN,NaN,NaN,CNE Head Office,CNE Head office,Credit Card,NaN,NaN,10719256454,NaN,NaN,NaN,NaN,NaN,beIN,BeIN sports CC,CNE Head office,NaN,Normal payment