In [ ]:

import pandas as pd


swap = pd.read_csv(r"S:\13.08.26\30732615_SWAPRPT.CSV",dtype='str')

In [3]:
swap

,Subscriber Number,Subscriber Type,Received Entity,Replacement Number,Item,Old Serial Number,New Serial Number,Swap Date,Swap Time,User Name
0,17459155,CNE Subscriber,Morad,97,Smartcard,10137612601,10509181003,12/05/2019 12:00:00 AM,12:41:34 PM,Shymaa Ahmed Abu Khalil
1,18812340,beIN Quartar Installment,Domiat,137,Smartcard,10508947289,10509036223,13/05/2019 12:00:00 AM,09:26:27 PM,Shereen abd allah El-Feky
2,18883014,beIN Bi Installment,beIN Alex,141,Decoder,0351959325,0349765459,13/05/2019 12:00:00 AM,10:58:42 PM,Karim Magdy
3,18678599,CNE Subscriber,Alex 5,173,Smartcard,10509213780,10509134895,15/05/2019 12:00:00 AM,10:15:17 PM,Ahmed Saad
4,16170769,beIN Bi Installment,Alex 3,176,Smartcard,10355753566,10508840245,16/05/2019 12:00:00 AM,12:49:50 PM,Amal Galal
...,...,...,...,...,...,...,...,...,...,...
63516,18166711,beIN Quartar Installment,beIN Gesr El Suies,50430,Decoder,0315382471,0381368436,11/08/2026 12:00:00 AM,01:20:42 PM,ABDALLAH DARWISH HAMED
63517,16270880,beIN Quartar Installment,Madinty,50432,Smartcard,10161623417,10739347341,11/08/2026 12:00:00 AM,02:33:37 PM,ABDALLAH DARWISH HAMED
63518,16573665,CNE Subscriber,Madinty,50435,Decoder,0315488929,0381360323,11/08/2026 12:00:00 AM,03:06:19 PM,ABDALLAH DARWISH HAMED
63519,19151602,CNE Subscriber,beIN Ahmed Orabey,50449,Smartcard,10730870911,10738878411,12/08/2026 12:00:00 AM,06:03:45 PM,Ahmed Mongi
63520,13928271,beIN Quartar Installment,Ismailia,50451,Decoder,0303318719,0373011087,12/08/2026 12:00:00 AM,07:42:22 PM,Ahmed Mongi

In [7]:

swap = swap[['Subscriber Number', 'Old Serial Number','New Serial Number','Swap Date']]
swap = swap.rename (columns={'Subscriber Number':'Customer Number'})

In [8]:
swap

,Customer Number,Old Serial Number,New Serial Number,Swap Date
0,17459155,10137612601,10509181003,12/05/2019 12:00:00 AM
1,18812340,10508947289,10509036223,13/05/2019 12:00:00 AM
2,18883014,0351959325,0349765459,13/05/2019 12:00:00 AM
3,18678599,10509213780,10509134895,15/05/2019 12:00:00 AM
4,16170769,10355753566,10508840245,16/05/2019 12:00:00 AM
...,...,...,...,...
63516,18166711,0315382471,0381368436,11/08/2026 12:00:00 AM
63517,16270880,10161623417,10739347341,11/08/2026 12:00:00 AM
63518,16573665,0315488929,0381360323,11/08/2026 12:00:00 AM
63519,19151602,10730870911,10738878411,12/08/2026 12:00:00 AM
63520,13928271,0303318719,0373011087,12/08/2026 12:00:00 AM